### ISSUE TITLE
Cricket does not work with Python 3.6

### ISSUE THREAD

**Issue by hop** [pybee/cricket#56]
Cricket does not work when using Python 3.6. Tracking down the issue, there is an import error in the (unmaintained?) tkreadonly library, which is still used as dependency by the (still maintained) cricket application.

The fix for tkreadonly that makes it work with Python 3.6 and earlier is here:
https://github.com/pybee-attic/tkreadonly/pull/2

**Comment by freakboy3742** [comment]
Thanks for the report!

I've just merged that patch, and released tkReadOnly v0.6.1. If you `pip install --update tkReadOnly`, cricket should now work under Python 3.6. 

In the (hopefully) not too long term future, I'm hoping to modify Cricket to use Toga, removing the need for tkReadonly.

**Comment by hop** [comment]
Awesome, thanks!

FYI, we used this yesterday at our local Python user group to give a talk on how to diagnose and report bugs and send pull requests to open source projects. I'll let them know that our fix is already accepted :)
